name: Maven Deploy

on:
  release:
    types: [published, created, edited]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/checkout@v2
    - name: Set up Maven Repository
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: lorenzo0111
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MVN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
