# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Release
       uses: qcastel/github-actions-maven-release@master
       with:
            git-release-bot-name: "GitHub Releases"
            release-branch-name: "release"
